# Generated by Django 6.0 on 2025-12-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('guitar', 'Guitarra'), ('piano', 'Piano'), ('violin', 'Violín'), ('drums', 'Batería'), ('singing', 'Canto'), ('music_theory', 'Teoría Musical')], max_length=50)),
                ('course_type', models.CharField(choices=[('online', 'En Línea'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('duration_weeks', models.IntegerField()),
                ('total_lessons', models.IntegerField()),
                ('schedule', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('video_url', models.URLField(blank=True)),
                ('materials', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
